### PR TITLE
Fix TrueNAS Scale build

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Review by themylogin — APPROVED** [review]

**Comment by yocalebo** [comment]
The build is already working?

**Comment by yocalebo** [comment]
Why did http://ci.tn.ixsystems.com/jenkins/job/Pull%20Requests/job/TrueNAS%20SCALE/job/PR%20-%20truenas-build/ that complete but the incremental build ail?

**Comment by sonicaj** [comment]
Because scale build is using the proposed middleware changes which will also btw fail on running of middleware as that package would never be pulled in the depends and will only be installed for biulding middleware.

**Comment by yocalebo** [comment]
What an absolute nightmare.

**Comment by sonicaj** [comment]
Yeah, although the debian package for py-fenced should be fixed which these changes do, so we are good.
About scale build using the same branch as the PR which was opened, that actually helps in the workflow of devs

**Comment by yocalebo** [comment]
Thanks for the help, nonetheless 😄

**Pull request merged**
